### ISSUE TITLE
[wont-fix] What license is this code shared under?

### ISSUE THREAD

**Issue by S0AndS0** [magical-mishka/tcw-chrome-extension#2]
Without an expressed license many regions will default to a state of "All rights reserved". Generally I prefer to contribute to Open Source projects, because there's more freedoms and less chances of litigation.

While I often use the AGPL-3.0 license for my projects, there are plenty of other options out there, and the [`https://opensource.guide/legal/`](https://opensource.guide/legal/) tips and [`https://choosealicense.com/appendix/`](https://choosealicense.com/appendix/) chart may be worth review prior to deciding if this project should become Open Source.

**Comment by magical-mishka** [comment]
Thanks for your interest! For this project, there is no license. Terms are explained in Readme.md

**Comment by S0AndS0** [comment]
That is an unfortunate course that I'll encourage you and your team to reconsider.

As of the last time that I've reviewed that section of the ReadMe file;


- there are no protections for contributors
- there are no protections for maintainers
- liability is ambiguous
- IP rights and protections are ambiguous


These _red-flags_ in particular are a huge barrier that'll have to be dealt with before I'll be able to support this project through code review.


There are quite a few Open Source licenses that allow for commercial use, while offering liability protections, as well as keeping IP (Intellectual Property) rights unambiguous. That second link in this Issue's OP (Original Post) is by far one of the best charts for comparing popular Open Source licenses.

Let me know within seven days if this issue will be fixed, and I'll happily begin submitting Pull Requests.

**Comment by jabranr** [comment]
I agree with above comments. The minimum license that almost covers the same terms given in README.md is the [MIT license](https://opensource.org/licenses/MIT) but also removes barriers to entry for contributors and reviewers.

**Comment by S0AndS0** [comment]
Indeed the MIT license would be a close fit, though any good OS license will mitigate chances of litigation minded individuals from treating projects as a sandcastle. Which is one of the primary reasons that repositories I contribute to and/or maintain are published under at least one Open Source license.

Unfortunately seven days have gone and past, so I'll be closing this Issue. However, the authors are welcome to re-open and/or resolve this issue, and I may choose swing through again to assist.
